nama=input("siapa namamu?:")
sekolah=input("sekolah dimana?:")
kelas=input("kelas berapa?:")
jurusan=input("masuk jurusan mana?:")
hobi=input("apa hobimu?:")
umur=input("brp umurmu?:")
makanan=input("makanan kesukaan?:")
game=input("game kesukaan?:") 
motor=input("motor kesukaan?:")
minum=input("minum kesukaan?:")
print("halo,nama saya",nama,"saya bersekloh di",sekolah,"saya kelas",kelas,"saya jurusan",jurusan,"hobi saya",hobi,"umur saya",umur,"makanan kesukaaan",makanan,"game saya",game,"motor kesukaan",motor,"minuman kesukan",minum)